### ISSUE TITLE
Update of Specific Package on Set of Packages

### ISSUE THREAD

**Issue by abarrak** [SimonCropp/PackageUpdate#13]
Hi,

Thanks for the great tool.🌹

Please consider adding support for updating single, or multiple packages only when they are passed.

**Comment by SimonCropp** [comment]
@abarrak sorry. for some reason i wasnt watching this repo. i will look into this

**Comment by SimonCropp** [comment]
https://github.com/SimonCropp/PackageUpdate#package

**Comment by SimonCropp** [comment]
This is now deployed. NuGet may take some time to make it available for download.
